from blind_watermark.blind_watermark import WaterMark

wm=WaterMark()
wm.embed_text("kdpowqkokxoemcopwmopwmqxopqewoximopqwmjxoirmqwioemoimqxipormxrpiqmwepomxpoiweqmxpomewqpomxowqmeopimqwopmxeopiwqmxpoirmqwpeomxpowqmepxmqpwmxpoiwqmeixopmqwxiopmasdfopspa,xpo,xop,ksopxopa,xpopxpoa,xpo,eapo,xpow,xpoe,wa,ex,iopawjeifiwaefoawmnfiomwaofemiowmfiowemfoiawmiofiowjefojwaeiofpjwioajefiowjifojwoajeiofjwiojefioewajefioejwaeoijaiwoejfoiawnefonamwuienfpawnfepawonfeoiawnfpawnefopnawoeifnowaenfpowe","./image_test/20.2.png","test_embed.png",only_meta_data=True)
print(wm.extract_text("test_embed.png"))

